"""
$ python ugrid2shp.py -n http://opendap.renci.org:1935/thredds/dodsC/ASGS/nam/2014112112/nc6b/hatteras.renci.org/rencidaily/namforecast/maxele.63.nc  -o test_thredds -a 0 -b 11 
http://opendap.renci.org:1935/thredds/dodsC/ASGS/nam/2014112112/nc6b/hatteras.renci.org/rencidaily/namforecastmaxele.63.nc
Getting data from http://opendap.renci.org:1935/thredds/dodsC/ASGS/nam/2014112112/nc6b/hatteras.renci.org/rencidaily/namforecast/maxele.63.nc...
Triangulating ...
Making contours in figure ...
Calling tricontourf  ...
Extracting contour shapes from tricontourf object ...
Writing shapes to test_thredds.shp
Writing prj to test_thredds.prj
Flushing zip file to test_thredds.zip
"""
if __name__ == '__main__':
	import shelldoctest
	shelldoctest.testmod(verbose=3)
