#!/usr/local/bin/python
"""
$ python ugrid2shp.py -o test_local -a 0 -b 11
file://maxele.63.nc
Getting data from maxele.63.nc... 
Triangulating ...
Making contours in figure ...
Calling tricontourf  ...
Extracting contour shapes from tricontourf object ...
Writing shapes to test_local.shp
Writing prj to test_local.prj
Flushing zip file to test_local.zip
"""
if __name__ == '__main__':
	import shelldoctest
	shelldoctest.testmod(verbose=3)
